### ISSUE TITLE
为什么会这样？数据出不来

### ISSUE THREAD

**Issue by PearLinger** [zhaobao/vue-table#4]
![image](https://user-images.githubusercontent.com/21024206/53236707-e6cf8280-36cf-11e9-95be-79fa9612c476.png)
![image](https://user-images.githubusercontent.com/21024206/53236722-ee8f2700-36cf-11e9-84a0-155a2d99c6b3.png)

**Comment by PearLinger** [comment]
请您有空的时候帮忙回复一下 谢谢了

**Comment by zhaobao** [comment]
@PearLinger 这是你API那边的错误，请求的地址不可用，这个项目是基于服务端的，需要有服务端的配合，你可以修改API部分参数，改成自己的server地址
